name: Deploy to WordPress.org

on:
  push:
    tags:
    - "*"

jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
    - name: Deploying Dummy Images
      uses: 10up/action-wordpress-plugin-deploy@master
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
